package EduMentor_dummy_project.src;

import java.sql.Timestamp;

public class Student {
    private int id;
    private String name;
    private String email;
    private String password;
    private String gradeLevel;
    private Timestamp registrationDate;

    // Constructor when registrationDate is provided (for existing students from database)
    public Student(int id, String name, String email, String password, String gradeLevel, Timestamp registrationDate) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.gradeLevel = gradeLevel;
        this.registrationDate = registrationDate;
    }

    // Constructor for new student (registrationDate is auto-generated in the database)
    public Student(int id, String name, String email, String password, String gradeLevel) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.gradeLevel = gradeLevel;
        this.registrationDate = null;  // registrationDate will be auto-generated by MySQL
    }

    // Getters
    public int getId() { return id; }
    public String getName() { return name; }
    public String getEmail() { return email; }
    public String getPassword() { return password; }
    public String getGradeLevel() { return gradeLevel; }
    public Timestamp getRegistrationDate() { return registrationDate; }
}
